spring:
  application:
    name: Taller-Tienda

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tallerAR?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:MiClaveSegura123!}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:false}

server:
  port: ${APP_PORT:8080}
